### ISSUE TITLE
Different message type for MAM messages

### ISSUE THREAD

**Issue by aarjan** [vavadiyahiren/xmpp_plugin#58]
While sending messages using **sendMessage** or calling **requestMamMessages**, 
the messages are obtained in the same **onNormalMessage** callback events. So, it's hard to to differentiate the archived messages from callback messages.

It will be helpful during pagination while paginating archived messages. 
Right now, i am sorting the messages by timestamp which is very compute expensive.

**Comment by vavadiyahiren** [comment]
@aarjan I believe you are testing on the ios version, The way xmpp framework behaves that way so does this plugin as well.

However let me see if i can add any extra flag to identify this kind of MAM messages.

**Comment by jennifercardenasm** [comment]
Hi there!!

I have the same issue, because when the **requestMamMessages** is called, all the messages are given by onChatMessage method which are provided by the DataChangeEvents interface. I got this output printing the object gaved by the event, something like this: 

```
 @override
  void onChatMessage(MessageChat messageChat) {  logger.d("SessionChats~~>onChatMessage  ================================================================== "
        "\n ${messageChat.toEventData()}");

```

I have saved some information from messageChat Object gotten from every event resulting. In the log, you can see it as mscontentList: 4 {token: null, content: hola, type: Message, addTime: 2023-11-08 17:38:24.799, to: null, from: prueba3, id: 1699486704796, chatStateType: } but I guess i am only speculating, because I dont know for sure if the message gotten is from the person who I am gettin the historic of chats

```
I/flutter ( 9770): [D]  SessionChats~~>onChatMessage  ================================================================== 
I/flutter ( 9770):  {customText: , from: prueba4@myserver/Android, senderJid: prueba4@myserver/Android, time: 1699066150117, id: 1699066150105, type: Message, body: ttt, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0, delayTime: 0, chatStateType: }
I/flutter ( 9770): [D]  mscontentList: 1 {token: null, content: ttt, type: Message, addTime: 2023-11-03 20:49:10.117null, from: prueba4, id: 1699066150105, chatStateType: }
[GETX] GOING TO ROUTE /chat?doc_id&to_username=prueba4&to_token&to_name=Usuario+pruebas+cuatro&to_avatar=http%3A%2F%2Fec2-3-211-171-168.compute-1.amazonaws.com%3A9090%2Fimages%2Flogin_logo.gif&to_online=null
I/flutter ( 9770): [D]  SessionChats~~>onChatMessage  ================================================================== 
I/flutter ( 9770):  {customText: , from: prueba4@myserver/Android, senderJid: prueba4@myserver/Android, time: 1699486116634, id: 1699486116628, type: Message, body: hi, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0, delayTime: 0, chatStateType: }
I/flutter ( 9770): [D]  mscontentList: 2 {token: null, content: hi, type: Message, addTime: 2023-11-08 17:28:36.634null, from: prueba4, id: 1699486116628, chatStateType: }
I/flutter ( 9770): [D]  SessionChats~~>onChatMessage  ================================================================== 
I/flutter ( 9770):  {customText: , from: prueba4@myserver/Android, senderJid: prueba4@myserver/Android, time: 1699486410574, id: 1699486410562, type: Message, body: holi, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0, delayTime: 0, chatStateType: }
I/flutter ( 9770): [D]  mscontentList: 3 {token: null, content: holi, type: Message, addTime: 2023-11-08 17:33:30.574null, from: prueba4, id: 1699486410562, chatStateType: }
I/flutter ( 9770): [D]  SessionChats~~>onChatMessage  ================================================================== 
I/flutter ( 9770):  {customText: , from: prueba3@myserver/Android, senderJid: prueba3@myserver/Android, time: 1699486704799, id: 1699486704796, type: Message, body: hola, msgtype: chat, bubbleType: , mediaURL: , isReadSent: 0, delayTime: 0, chatStateType: }
I/flutter ( 9770): [D]  mscontentList: 4 {token: null, content: hola, type: Message, addTime: 2023-11-08 17:38:24.799null, from: prueba3, id: 1699486704796, chatStateType: }

```
Far away from my last explanaition i found another issue, at the beginin of the process I notice an exception. This is the log gotten:

D/flutter_xmpp( 9770):  onMethodCall call: request_mam
D/flutter_xmpp( 9770): userJId prueba4@myserver Before : 1699556349742 since 1698692349742 limit 1000
D/flutter_xmpp( 9770): MAM query Args org.jivesoftware.smackx.mam.MamManager$MamQueryArgs$Builder@296eee9
D/SMACK   ( 9770): SENT (0): <iq id='9HnR5-675' type='set'><query xmlns='urn:xmpp:mam:1' queryid='e2002311-e703-4592-a40f-994299bd60e2'><x xmlns='jabber:x:data' type='submit'><field var='FORM_TYPE' type='hidden'><value>urn:xmpp:mam:1</value></field><field var='start'><value>2023-10-30T18:59:09.742+00:00</value></field><field var='with'><value>prueba4@myserver</value></field><field var='end'><value>2023-11-09T18:59:09.742+00:00</value></field></x><set xmlns='http://jabber.org/protocol/rsm'><max>1000</max></set></query></iq>
D/SMACK   ( 9770): RECV (0): <message to="prueba3@myserver/Android"><result xmlns="urn:xmpp:mam:1" queryid="e2002311-e703-4592-a40f-994299bd60e2" id="4"><forwarded xmlns="urn:xmpp:forward:0"><delay xmlns="urn:xmpp:delay" stamp="2023-11-04T02:49:07.953Z"/><message xmlns="jabber:client" to="prueba3@myserver" id="1699066150105" type="chat" from="prueba4@myserver/Android"><body>ttt</body><TIME xmlns="urn:xmpp:time"><ts>1699066150117</ts></TIME><request xmlns="urn:xmpp:receipts"></request></message></forwarded></result></message>
**I/System.out( 9770): From:null body:null  StanzaId: null message:Message Stanza [to=prueba3@myserver/Android,]
E/AbstractXMPPConnection( 9770): Exception in packet listener
E/AbstractXMPPConnection( 9770): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.jxmpp.jid.Jid.toString()' on a null object reference
E/AbstractXMPPConnection( 9770): 	at org.xrstudio.xmpp.flutter_xmpp.Utils.Utils.broadcastMessageToFlutter(Utils.java:174)
E/AbstractXMPPConnection( 9770): 	at org.xrstudio.xmpp.flutter_xmpp.listner.MessageListener.processStanza(MessageListener.java:22)
E/AbstractXMPPConnection( 9770): 	at org.jivesoftware.smack.AbstractXMPPConnection$7.run(AbstractXMPPConnection.java:1271)
E/AbstractXMPPConnection( 9770): 	at org.jivesoftware.smack.AsyncButOrdered$Handler.run(AsyncButOrdered.java:135)
E/AbstractXMPPConnection( 9770): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/AbstractXMPPConnection( 9770): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/AbstractXMPPConnection( 9770): 	at java.lang.Thread.run(Thread.java:1012)**
D/SMACK   ( 9770): RECV (0): <message to="prueba3@myserver/Android"><result xmlns="urn:xmpp:mam:1" queryid="e2002311-e703-4592-a40f-994299bd60e2" id="386"><forwarded xmlns="urn:xmpp:forward:0"><delay xmlns="urn:xmpp:delay" stamp="2023-11-08T23:28:36.209Z"/><message xmlns="jabber:client" to="prueba3@myserver" id="1699486116628" type="chat" from="prueba4@myserver/Android"><body>hi</body><TIME xmlns="urn:xmpp:time"><ts>1699486116634</ts></TIME><request xmlns="urn:xmpp:receipts"></request></message></forwarded></result></message>
D/SMACK   ( 9770): RECV (0): <r xmlns='urn:xmpp:sm:3' />
D/SMACK   ( 9770): SENT (0): <a xmlns='urn:xmpp:sm:3' h='340'/>
D/SMACK   ( 9770): RECV (0): <message to="prueba3@myserver/Android"><result xmlns="urn:xmpp:mam:1" queryid="e2002311-e703-4592-a40f-994299bd60e2" id="387"><forwarded xmlns="urn:xmpp:forward:0"><delay xmlns="urn:xmpp:delay" stamp="2023-11-08T23:33:30.174Z"/><message xmlns="jabber:client" to="prueba3@myserver" id="1699486410562" type="chat" from="prueba4@myserver/Android"><body>holi</body><TIME xmlns="urn:xmpp:time"><ts>1699486410574</ts></TIME><request xmlns="urn:xmpp:receipts"></request></message></forwarded></result></message>
D/SMACK   ( 9770): RECV (0): <message to="prueba3@myserver/Android"><result xmlns="urn:xmpp:mam:1" queryid="e2002311-e703-4592-a40f-994299bd60e2" id="388"><forwarded xmlns="urn:xmpp:forward:0"><delay xmlns="urn:xmpp:delay" stamp="2023-11-08T23:38:25.258Z"/><message xmlns="jabber:client" to="prueba4@myserver" id="1699486704796" type="chat" from="prueba3@myserver/Android"><body>hola</body><TIME xmlns="urn:xmpp:time"><ts>1699486704799</ts></TIME><request xmlns="urn:xmpp:receipts"></request></message></forwarded></result></message>
I/System.out( 9770): From:null body:null  StanzaId: null message:Message Stanza [to=prueba3@myserver/Android,]
E/AbstractXMPPConnection( 9770): Exception in packet listener
E/AbstractXMPPConnection( 9770): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.jxmpp.jid.Jid.toString()' on a null object reference
E/AbstractXMPPConnection( 9770): 	at org.xrstudio.xmpp.flutter_xmpp.Utils.Utils.broadcastMessageToFlutter(Utils.java:174)
E/AbstractXMPPConnection( 9770): 	at org.xrstudio.xmpp.flutter_xmpp.listner.MessageListener.processStanza(MessageListener.java:22)
E/AbstractXMPPConnection( 9770): 	at org.jivesoftware.smack.AbstractXMPPConnection$7.run(AbstractXMPPConnection.java:1271)
E/AbstractXMPPConnection( 9770): 	at org.jivesoftware.smack.AsyncButOrdered$Handler.run(AsyncButOrdered.java:135)
E/AbstractXMPPConnection( 9770): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/AbstractXMPPConnection( 9770): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/AbstractXMPPConnection( 9770): 	at java.lang.Thread.run(Thread.java:1012)
D/SMACK   ( 9770): RECV (0): <iq type="result" id="9HnR5-675" from="prueba3@myserver" to="prueba3@myserver/Android"><fin xmlns="urn:xmpp:mam:1" queryid="e2002311-e703-4592-a40f-994299bd60e2" complete="true"><set xmlns="http://jabber.org/protocol/rsm"><first>4</first><last>388</last><count>4</count></set></fin></iq>
D/flutter_xmpp( 9770): Received Message <message xmlns='jabber:client' to='prueba3@myserver' from='prueba4@myserver/Android' id='1699066150105' type='chat'><body>ttt</body><TIME xmlns='urn:xmpp:time' xmlns:stream='http://etherx.jabber.org/streams'><ts xmlns:stream='http://etherx.jabber.org/streams'>1699066150117</ts></TIME><request xmlns='urn:xmpp:receipts'/></message>
I/System.out( 9770): From:prueba4@myserver/Android body:ttt  StanzaId: 1699066150105 message:Message Stanza [to=prueba3@myserver,from=prueba4@myserver/Android,id=1699066150105,type=chat,]
I/System.out( 9770): From:null body:null  StanzaId: null message:Message Stanza [to=prueba3@myserver/Android,]
E/AbstractXMPPConnection( 9770): Exception in packet listener
E/AbstractXMPPConnection( 9770): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.jxmpp.jid.Jid.toString()' on a null object reference
E/AbstractXMPPConnection( 9770): 	at org.xrstudio.xmpp.flutter_xmpp.Utils.Utils.broadcastMessageToFlutter(Utils.java:174)
E/AbstractXMPPConnection( 9770): 	at org.xrstudio.xmpp.flutter_xmpp.listner.MessageListener.processStanza(MessageListener.java:22)
E/AbstractXMPPConnection( 9770): 	at org.jivesoftware.smack.AbstractXMPPConnection$7.run(AbstractXMPPConnection.java:1271)
E/AbstractXMPPConnection( 9770): 	at org.jivesoftware.smack.AsyncButOrdered$Handler.run(AsyncButOrdered.java:135)
E/AbstractXMPPConnection( 9770): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/AbstractXMPPConnection( 9770): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/AbstractXMPPConnection( 9770): 	at java.lang.Thread.run(Thread.java:1012)
D/flutter_xmpp( 9770): Received Message <message xmlns='jabber:client' to='prueba3@myserver' from='prueba4@myserver/Android' id='1699486116628' type='chat'><body>hi</body><TIME xmlns='urn:xmpp:time' xmlns:stream='http://etherx.jabber.org/streams'><ts xmlns:stream='http://etherx.jabber.org/streams'>1699486116634</ts></TIME><request xmlns='urn:xmpp:receipts'/></message>
I/System.out( 9770): From:prueba4@myserver/Android body:hi  StanzaId: 1699486116628 message:Message Stanza [to=prueba3@myserver,from=prueba4@myserver/Android,id=1699486116628,type=chat,]
D/flutter_xmpp( 9770): Received Message <message xmlns='jabber:client' to='prueba3@myserver' from='prueba4@myserver/Android' id='1699486410562' type='chat'><body>holi</body><TIME xmlns='urn:xmpp:time' xmlns:stream='http://etherx.jabber.org/streams'><ts xmlns:stream='http://etherx.jabber.org/streams'>1699486410574</ts></TIME><request xmlns='urn:xmpp:receipts'/></message>
I/System.out( 9770): From:prueba4@myserver/Android body:holi  StanzaId: 1699486410562 message:Message Stanza [to=prueba3@myserver,from=prueba4@myserver/Android,id=1699486410562,type=chat,]
D/flutter_xmpp( 9770): Received Message <message xmlns='jabber:client' to='prueba4@myserver' from='prueba3@myserver/Android' id='1699486704796' type='chat'><body>hola</body><TIME xmlns='urn:xmpp:time' xmlns:stream='http://etherx.jabber.org/streams'><ts xmlns:stream='http://etherx.jabber.org/streams'>1699486704799</ts></TIME><request xmlns='urn:xmpp:receipts'/></message>
I/System.out( 9770): From:prueba3@myserver/Android body:hola  StanzaId: 1699486704796 message:Message Stanza [to=prueba4@myserver,from=prueba3@myserver/Android,id=1699486704796,type=chat,]
I/System.out( 9770): From:null body:null  StanzaId: null message:Message Stanza [to=prueba3@myserver/Android,]
D/TAG     ( 9770):  RECEIVE_MESSAGE-->> {chatStateType=, customText=, from=prueba4@myserver/Android, senderJid=prueba4@myserver/Android, delayTime=0, id=1699066150105, time=1699066150117, type=Message, body=ttt, msgtype=chat}
E/AbstractXMPPConnection( 9770): Exception in packet listener
E/AbstractXMPPConnection( 9770): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.jxmpp.jid.Jid.toString()' on a null object reference
E/AbstractXMPPConnection( 9770): 	at org.xrstudio.xmpp.flutter_xmpp.Utils.Utils.broadcastMessageToFlutter(Utils.java:174)
E/AbstractXMPPConnection( 9770): 	at org.xrstudio.xmpp.flutter_xmpp.listner.MessageListener.processStanza(MessageListener.java:22)
E/AbstractXMPPConnection( 9770): 	at org.jivesoftware.smack.AbstractXMPPConnection$7.run(AbstractXMPPConnection.java:1271)
E/AbstractXMPPConnection( 9770): 	at org.jivesoftware.smack.AsyncButOrdered$Handler.run(AsyncButOrdered.java:135)
E/AbstractXMPPConnection( 9770): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/AbstractXMPPConnection( 9770): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/AbstractXMPPConnection( 9770): 	at java.lang.Thread.run(Thread.java:1012)
D/TAG     ( 9770):  RECEIVE_MESSAGE-->> {chatStateType=, customText=, from=prueba4@myserver/Android, senderJid=prueba4@myserver/Android, delayTime=0, id=1699486116628, time=1699486116634, type=Message, body=hi, msgtype=chat}
D/TAG     ( 9770):  RECEIVE_MESSAGE-->> {chatStateType=, customText=, from=prueba4@myserver/Android, senderJid=prueba4@myserver/Android, delayTime=0, id=1699486410562, time=1699486410574, type=Message, body=holi, msgtype=chat}
D/TAG     ( 9770):  RECEIVE_MESSAGE-->> {chatStateType=, customText=, from=prueba3@myserver/Android, senderJid=prueba3@myserver/Android, delayTime=0, id=1699486704796, time=1699486704799, type=Message, body=hola, msgtype=chat}

**Comment by vavadiyahiren** [comment]
@jennifercardenasm Exception must have been addressed. 

If you still not found a way book a calendar with me i can help you : hiren@xrstudio.in
